# Generated by Django 2.1.3 on 2018-11-25 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kierunek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('typ', models.CharField(choices=[('stacjonarny', 'Stacjonarne'), ('niestacjonarny', 'Niestacjonarne')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KierunekStudenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kierunek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studenci', to='students.Kierunek')),
            ],
        ),
        migrations.CreateModel(
            name='PracaNaukowa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('wydana', 'Wydana'), ('tworzona', 'Tworzona'), ('plagiat', 'PLAGIAT 💩')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Promotor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('stopien', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('kierunki', models.ManyToManyField(through='students.KierunekStudenta', to='students.Kierunek')),
            ],
        ),
        migrations.AddField(
            model_name='pracanaukowa',
            name='promotor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prace_naukowe', to='students.Promotor'),
        ),
        migrations.AddField(
            model_name='pracanaukowa',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prace_naukowe', to='students.Student'),
        ),
        migrations.AddField(
            model_name='kierunekstudenta',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wybrane_kierunki', to='students.Student'),
        ),
    ]
